version: '2'
services:
  mongo:
      image: mongo
      restart: always
      ports:
        - 27018:27018
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: secret
